package com.andruhavuho.man.like.kcalcalc.contracts

const val PICKED_SPORT_ID = "PICKED_SPORT_ID"
const val PICKED_SPORT_NAME = "PICKED_SPORT_NAME"
const val PICKED_SPORT_NUM_HOURS = "PICKED_SPORT_NUM_HOURS"
const val PICKED_SPORT_NUM_MINUTES = "PICKED_SPORT_NUM_MINUTES"
const val PICKED_SPORT_KCAL_PER_HOUR = "PICKED_SPORT_KCAL_PER_HOUR"
